# Generated by Django 4.2 on 2023-04-30 14:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("photoAlbum", "0001_initial"),
        ("shelterRelated", "0002_contactinfo_x_cord_contactinfo_y_cord"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shelter",
            name="contact_info",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="shelterRelated.contactinfo",
            ),
        ),
        migrations.AlterField(
            model_name="shelter",
            name="photo_album",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="photoAlbum.photoalbum",
            ),
        ),
    ]
