# Generated by Django 4.2 on 2023-04-26 19:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    initial = True

    dependencies = [
        ("shelterRelated", "0001_initial"),
        ("photoAlbum", "0001_initial"),
    ]

    operations = [
        migrations.CreateModel(
            name="PetCharacteristics",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("species", models.CharField(max_length=255)),
                ("subSpecies", models.CharField(max_length=255)),
                ("age", models.IntegerField()),
                ("gender", models.CharField(max_length=255)),
                ("color", models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name="Pet",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=255)),
                (
                    "petCharacteristics",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adRelated.petcharacteristics",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="AdFilters",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "petCharacteristics",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="adRelated.petcharacteristics",
                    ),
                ),
            ],
        ),
        migrations.CreateModel(
            name="Ad",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("active", models.BooleanField()),
                (
                    "pet",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE, to="adRelated.pet"
                    ),
                ),
                (
                    "photoAlbum",
                    models.ForeignKey(
                        null=True,
                        on_delete=django.db.models.deletion.CASCADE,
                        to="photoAlbum.photoalbum",
                    ),
                ),
                (
                    "shelter",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.CASCADE,
                        to="shelterRelated.shelter",
                    ),
                ),
            ],
        ),
    ]
