# Generated by Django 4.2 on 2023-05-02 18:41

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("adRelated", "0001_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="ad",
            old_name="photoAlbum",
            new_name="photo_album",
        ),
        migrations.RemoveField(
            model_name="pet",
            name="petCharacteristics",
        ),
        migrations.AddField(
            model_name="ad",
            name="share_link",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="pet",
            name="age",
            field=models.IntegerField(default=0),
        ),
        migrations.AddField(
            model_name="pet",
            name="color",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="pet",
            name="gender",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="pet",
            name="species",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AddField(
            model_name="pet",
            name="subSpecies",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.AlterField(
            model_name="pet",
            name="name",
            field=models.CharField(default="", max_length=255),
        ),
        migrations.DeleteModel(
            name="AdFilters",
        ),
        migrations.DeleteModel(
            name="PetCharacteristics",
        ),
    ]
