# Generated by Django 4.2 on 2023-05-02 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):
    dependencies = [
        ("photoAlbum", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="photo",
            name="photo_album",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="photos",
                to="photoAlbum.photoalbum",
            ),
        ),
    ]
