name: Format python with black in BackendApp
run-name: ${{ github.head_ref }} is formatting python 🚀
on:
  pull_request:
    branches:
      - master
    paths:
      - BackendApp/**/*.py
  push:
    branches:
      - master
    paths:
      - BackendApp/**/*.py
jobs:
  Check-formatting:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Install black
        run: python3 -m pip install black
      - name: Check formatting
        id: check
        working-directory: BackendApp
        run: python3 -m black --check --quiet .
      - name: Display unformatted files
        working-directory: BackendApp
        if: failure() && steps.check.outcome == 'failure'
        run: python3 -m black --diff --quiet .
