name: Frontend jest unit tests
run-name: ${{ github.triggering_actor }} is running '${{ github.workflow }}' on '${{ github.ref }}'.
on:
  pull_request:
    branches:
      - master
  push:
    branches:
      - master
jobs:
  Test:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install node dependencies in MeowdoptMeApp
        working-directory: MeowdoptMeApp
        run: yarn
      - name: Run unit tests
        working-directory: MeowdoptMeApp
        run: yarn test
