name: Lint python
run-name: ${{ github.head_ref }} is linting python 🚀
on:
  pull_request:
    branches:
      - master
    paths:
      - BackendApp/**/*.py
  push:
    branches:
      - master
    paths:
      - BackendApp/**/*.py
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Setup backend
        working-directory: BackendApp
        run: make setup && source env/bin/activate && make requirements
      - name: Lint
        working-directory: BackendApp
        run: source env/bin/activate && make lint
