name: Lint root
run-name: ${{ github.head_ref }} is linting 🚀
on:
  pull_request:
    branches:
      - master
    paths-ignore:
      - BackendApp
      - diagrams
  push:
    branches:
      - master
    paths-ignore:
      - BackendApp
      - diagrams
jobs:
  Lint:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v3
      - name: Use Node.js 18
        uses: actions/setup-node@v3
        with:
          node-version: 18
          cache: 'yarn'
      - name: Install node dependencies
        run: yarn
      - name: Check
        run: yarn static-checks
